CREATE USER IF NOT EXISTS 'Jhoan'@'%' IDENTIFIED BY '1217';
GRANT ALL PRIVILEGES ON *.* TO 'Jhoan'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS money_control
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE money_control;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(40) NOT NULL,
    lastname VARCHAR(40) NOT NULL,
    password VARCHAR(255) NOT NULL,
    telefono VARCHAR(10) NOT NULL,
    email VARCHAR(40) NOT NULL,
    pais VARCHAR(40),
    nacimiento DATE NOT NULL,
    genero ENUM('masculino', 'femenino', 'no_binario', 'prefiero_no_decir') DEFAULT 'prefiero_no_decir',
    fecha_de_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tipo_de_usuario INT DEFAULT 1,
    duracion_tipo_de_usuario INT DEFAULT NULL, --DURACION DE UN USUARIO PREMIUM
)

CREATE TABLE IF NOT EXISTS sugerencias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    calificacion INT NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario VARCHAR(300) NOT NULL,
    usuario INT NOT NULL,
    tipo_sugerencia INT NOT NULL,
    FOREIGN KEY (usuario) REFERENCES usuarios(id),
    FOREIGN KEY (tipo_sugerencia) REFERENCES tipo_de_sugerencia(id)
);



--Pagos
CREATE TABLE IF NOT EXTIST pagos
id INT AUTO_INCREMENT PRIMARY KEY
tipo_de_pago VARCHAR(100) NOT NULL


--gastos
CREATE TABLE IF NOT EXISTS gastos
id INT AUTO_INCREMENT PRIMARY KEY
valor INT AUTO_INCREMENT PRIMARY KEY
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--ingresos
CREATE TABLE IF NOT EXISTS ingresos
id INT AUTO_INCREMENT PRIMARY KEY
valor INT AUTO_INCREMENT PRIMARY KEY
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--tipo de sugerencias
CREATE TABLE IF NOT EXISTS tipo_sugerencia
id INT AUTO_INCREMENT PRIMARY KEY
nombre_tipo_sugerencia VARCHAR(100) NOT NULL

--categoria gastos
CREATE TABLE IF NOT EXISTS categoria_gastos
id INT AUTO_INCREMENT PRIMARY KEY
nombre VARCHAR(100) NOT NULL
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

--categoria ingresos
CREATE TABLE IF NOT EXISTS categoria_ingresos
id INT AUTO_INCREMENT PRIMARY KEY
nombre VARCHAR(100) NOT NULL
id_usuario INT AUTO_INCREMENT PRIMARY KEY --CLAVE FORANEA

CREATE TABLE IF NOT EXISTS tipo_de_sugerencia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo_de_sugerencia VARCHAR(100) NOT NULL
);