CREATE USER IF NOT EXISTS 'Jhoan'@'%' IDENTIFIED BY '1217';
GRANT ALL PRIVILEGES ON *.* TO 'Jhoan'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS prueba
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE prueba;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    apellido VARCHAR(100),
    email VARCHAR(150)
);
